---
title: "Résumé Delmas et al 2019 - BIO500"
author: "Jonathan Rondeau-Leclaire, Amélie Harbeck-Bastien, Samuel Fortin"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Vocabulaire

- G = graph = réseau
- V = sommet (vertex) = Noeud (node) = étudiant
- E = Arc (edge) = collaboration = sous-ensemble de deux éléments de V
- A = matrice d'adjecence (ou d'incidence = pairwise P/A d'interactions (ou pondéré ≈ heatmap)
  - symétrique avec diag 0 si non-dirigé sans boucle

### Mesures

- $S$ = Ordre = nombre total de noeuds V. Ex. Richesse si espèces
- $L$ = Taille = nombre total d'arcs
- $L/S$ = Densité = moyenne d'interactions par noeud 
	- Attention à l'interprétation, n'est souvent pas uniforme!
  - $L$ est souvent proportionnel à $S^2$
- $m$ = nombre d'interactions possible dans un réseau (dépend du type de réseau!)
- $C_0$ = Connectance = $L/m$ (% interactions réalisées / possibles)
  - bonne mesure de sensibilité aux perturbations
  - Varie de 0 à 1 selon si A est vide ou pleine
- $P(k) = N(k)/S$ : probabilité qu'un noeud ait $k$ arcs; $N(k)$ est le nombre de noeuds ayant $k$ arcs. (C'est une moyenne en gros!)
- $k$ = degré = nombre de noeuds voisins
- $D$ = Diamètre = Le plus long des plus courts chemins entre chaque paire de noeuds, où $d_{i,j}$ représente le nombre d'interactions séparant le noeud $i$ du noeud $j$. Peut aussi être mesuré en distance moyenne entre chaque noeud du réseau pour normaliser par la taille du réseau.

- Motifs: $CC$ = coefficient de regroupement
  - $cc_i = \frac{2N_i}{k_i(k_i-1)}$, où $N_i$ = nombre d'interactions totales entre tous les voisins de $i$
  - fraction des interactions réalisées entre les voisins d'un noeud

- Module: Subsystem of non-overlapping and strongly interacting species. Pertinence?

- Emboîtement (nestedness): Pas pertinent
- Intervalité: expliquer les interactions d'un réseau par un gradient d'un trait commun. Méthodes non présentées

### Nos données

- Réseau unipartite simple non-dirigé, possiblement pondéré,
- Nos données sont des interactions réalisées
- Effort d'échantillonage: pratiquement exhaustif
- Aucune boucle (self-edge) ni multi-arcs
- Unipartite, car toutes les paires sont théoriquement possibles. Diffère des bipartite, où par exemple les arcs sont toujours faits entre des membres appartenant à deux groupes distincts (ex. proie-pred)

Matrice d'adjecence: $A_{S,S}$ où $a_{i,j} = a_{j,i} ∈ {0,1}$


### On pourrait calculer...
- Ordre, Taille, Densité, diamètre
- Connectance; dans un réseau unipartite simple non-dirigé, $m = S*\frac{S-1}{2}$


### On pourrait tester...

- Uniformité et normalité de la densité L/S?
- Distribution des degrés est-elle en puissance?
- y a-t-il une intervalité dans le réseau?
